// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComposeProject(arg1) {
  return window['go']['main']['App']['AddComposeProject'](arg1);
}

export function CancelImagePull(arg1) {
  return window['go']['main']['App']['CancelImagePull'](arg1);
}

export function ComposeDown(arg1) {
  return window['go']['main']['App']['ComposeDown'](arg1);
}

export function ComposeRestart(arg1) {
  return window['go']['main']['App']['ComposeRestart'](arg1);
}

export function ComposeUp(arg1) {
  return window['go']['main']['App']['ComposeUp'](arg1);
}

export function ConnectNetwork(arg1) {
  return window['go']['main']['App']['ConnectNetwork'](arg1);
}

export function CreateNetwork(arg1) {
  return window['go']['main']['App']['CreateNetwork'](arg1);
}

export function DeleteDockerContext(arg1) {
  return window['go']['main']['App']['DeleteDockerContext'](arg1);
}

export function DisconnectNetwork(arg1) {
  return window['go']['main']['App']['DisconnectNetwork'](arg1);
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function InspectImageRunConfig(arg1) {
  return window['go']['main']['App']['InspectImageRunConfig'](arg1);
}

export function InspectNetwork(arg1) {
  return window['go']['main']['App']['InspectNetwork'](arg1);
}

export function ListComposeProjects() {
  return window['go']['main']['App']['ListComposeProjects']();
}

export function ListContainers(arg1) {
  return window['go']['main']['App']['ListContainers'](arg1);
}

export function ListDockerContexts() {
  return window['go']['main']['App']['ListDockerContexts']();
}

export function ListImages(arg1) {
  return window['go']['main']['App']['ListImages'](arg1);
}

export function ListNetworks() {
  return window['go']['main']['App']['ListNetworks']();
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function PruneNetworks(arg1) {
  return window['go']['main']['App']['PruneNetworks'](arg1);
}

export function PullImage(arg1) {
  return window['go']['main']['App']['PullImage'](arg1);
}

export function RemoveContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2);
}

export function RemoveImage(arg1, arg2) {
  return window['go']['main']['App']['RemoveImage'](arg1, arg2);
}

export function RemoveNetwork(arg1, arg2) {
  return window['go']['main']['App']['RemoveNetwork'](arg1, arg2);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function RunImage(arg1) {
  return window['go']['main']['App']['RunImage'](arg1);
}

export function SaveDockerContext(arg1) {
  return window['go']['main']['App']['SaveDockerContext'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopLogStream(arg1) {
  return window['go']['main']['App']['StopLogStream'](arg1);
}

export function StreamComposeLogs(arg1) {
  return window['go']['main']['App']['StreamComposeLogs'](arg1);
}

export function StreamContainerLogs(arg1) {
  return window['go']['main']['App']['StreamContainerLogs'](arg1);
}

export function SwitchDockerContext(arg1) {
  return window['go']['main']['App']['SwitchDockerContext'](arg1);
}

export function TestDockerContext(arg1) {
  return window['go']['main']['App']['TestDockerContext'](arg1);
}
