// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function AddComposeProject(arg1:core.AddComposeProjectRequestDTO):Promise<core.ComposeProjectDTO>;

export function CancelImagePull(arg1:string):Promise<core.ActionResultDTO>;

export function ComposeDown(arg1:string):Promise<core.ActionResultDTO>;

export function ComposeRestart(arg1:string):Promise<core.ActionResultDTO>;

export function ComposeUp(arg1:string):Promise<core.ActionResultDTO>;

export function ConnectNetwork(arg1:core.NetworkConnectRequestDTO):Promise<core.ActionResultDTO>;

export function CreateNetwork(arg1:core.NetworkCreateRequestDTO):Promise<core.ActionResultDTO>;

export function DeleteDockerContext(arg1:string):Promise<core.ActionResultDTO>;

export function DisconnectNetwork(arg1:core.NetworkDisconnectRequestDTO):Promise<core.ActionResultDTO>;

export function GetAppStatus():Promise<core.AppStatusDTO>;

export function InspectNetwork(arg1:core.NetworkInspectRequestDTO):Promise<core.NetworkInspectDTO>;

export function ListComposeProjects():Promise<Array<core.ComposeProjectDTO>>;

export function ListContainers(arg1:core.ContainerQueryDTO):Promise<Array<core.ContainerSummaryDTO>>;

export function ListDockerContexts():Promise<Array<core.DockerContextDTO>>;

export function ListImages(arg1:core.ImageQueryDTO):Promise<Array<core.ImageSummaryDTO>>;

export function ListNetworks():Promise<Array<core.NetworkDTO>>;

export function ListVolumes():Promise<Array<core.VolumeDTO>>;

export function PruneNetworks(arg1:core.NetworkPruneRequestDTO):Promise<core.ActionResultDTO>;

export function PullImage(arg1:core.ImagePullRequestDTO):Promise<core.StreamSubscriptionDTO>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<core.ActionResultDTO>;

export function RemoveImage(arg1:string,arg2:boolean):Promise<core.ActionResultDTO>;

export function RemoveNetwork(arg1:string,arg2:boolean):Promise<core.ActionResultDTO>;

export function RestartContainer(arg1:string):Promise<core.ActionResultDTO>;

export function SaveDockerContext(arg1:core.SaveDockerContextRequestDTO):Promise<core.DockerContextDTO>;

export function StartContainer(arg1:string):Promise<core.ActionResultDTO>;

export function StopContainer(arg1:string):Promise<core.ActionResultDTO>;

export function StopLogStream(arg1:string):Promise<core.ActionResultDTO>;

export function StreamComposeLogs(arg1:core.LogStreamRequestDTO):Promise<core.StreamSubscriptionDTO>;

export function StreamContainerLogs(arg1:core.LogStreamRequestDTO):Promise<core.StreamSubscriptionDTO>;

export function SwitchDockerContext(arg1:core.SwitchDockerContextRequestDTO):Promise<core.ActionResultDTO>;

export function TestDockerContext(arg1:string):Promise<core.DockerContextProbeDTO>;
